// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Employee struct {
	ID           string `json:"id"`
	FirstName    string `json:"firstName"`
	LastName     string `json:"lastName"`
	Username     string `json:"username"`
	Password     string `json:"password"`
	Email        string `json:"email"`
	Dob          string `json:"dob"`
	DepartmentID string `json:"departmentID"`
	Position     string `json:"position"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type EmployeeInput struct {
	FirstName    string `json:"firstName"`
	LastName     string `json:"lastName"`
	Username     string `json:"username"`
	Password     string `json:"password"`
	Email        string `json:"email"`
	Dob          string `json:"dob"`
	DepartmentID string `json:"departmentID"`
	Position     string `json:"position"`
}
